//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLibros.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaUsuario
    {
        public CuentaUsuario()
        {
            this.LibroPublicado = new HashSet<LibroPublicado>();
            this.Contacto = new HashSet<Contacto>();
        }
    
        public int Id_cuenta { get; set; }
        public string Nombre_cuenta { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public string Nombres { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public bool Administrador { get; set; }
    
        public virtual ICollection<LibroPublicado> LibroPublicado { get; set; }
        public virtual ICollection<Contacto> Contacto { get; set; }
    }
}
