//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLibros.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroPublicado
    {
        public int Id_libro { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public int Anno_publicacion { get; set; }
        public int Categoria { get; set; }
        public int Contenido { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad_paginas { get; set; }
        public int Cantidad_Votos { get; set; }
        public int Tipo_Estado { get; set; }
        public int Tipo_Periodicidad { get; set; }
        public string Portada { get; set; }
        public string Pdf { get; set; }
        public int Id_cuenta { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
    }
}
