//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLibros.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudbookEntities : DbContext
    {
        public CloudbookEntities()
            : base("name=CloudbookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CuentaUsuario> CuentaUsuario { get; set; }
        public DbSet<LibroComercial> LibroComercial { get; set; }
        public DbSet<LibroPublicado> LibroPublicado { get; set; }
        public DbSet<Contacto> Contacto { get; set; }
    }
}
